apiVersion: apps/v1

kind: Deployment

metadata:

  name: newdeploy
  namespace: myapp

  labels:

    app: myapp

spec:

  replicas: 1

  selector:

    matchLabels:

      app: myapp

  template:

    metadata:

      labels:

        app: myapp

    spec:

      containers:

      - name: python-app

        image: mostafa001/project-app:${BUILD_NUMBER}

        ports:

        - containerPort: 81
